baseURL = 'https://jamiebrunton.com'
languageCode = 'en-us'
title = 'Software Engineer'
theme = "anatole"

enableRobotsTXT = true

pygmentsCodeFences = true
pygmentsUseClasses = true
disqusShortname = 'jjbrunton'

[params]
title = "Jamie Brunton"
author = "Jamie Brunton"
description = "Software Engineer"
profilePicture = "images/profile.jpg"
readMore = true

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[menu]

  [[menu.main]]
  name = "Blog"
  identifier = "blog"
  weight = 1
  url = "/"
  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 100
  url = "/about"